apiVersion: v1
kind: Service
metadata:
  labels:
    app: topic-modeling
  name: topic-modeling
spec:
  #  type: LoadBalancer
  ports:
    - name: topic-modeling-service
      port: 5003
      targetPort: 5003
  selector:
    app: topic-modeling
